#!/bin/sh
# ─────────────────────────────────────────────────────────────────────────────
#  docker/entrypoint.sh
#
#  Generates db.php from environment variables injected by docker-compose,
#  then hands off to the CMD (apache2-foreground).
#
#  Required environment variables:
#    DB_HOST  — hostname of the MySQL container (default: "db")
#    DB_USER  — database username
#    DB_PASS  — database password
#    DB_NAME  — database name
# ─────────────────────────────────────────────────────────────────────────────

set -e

DB_HOST="${DB_HOST:-db}"
DB_USER="${DB_USER:-root}"
DB_PASS="${DB_PASS:-}"
DB_NAME="${DB_NAME:-college_announcement}"

# Write db.php into the web root (this file is gitignored)
cat > /var/www/html/db.php <<PHP
<?php
// Auto-generated by docker/entrypoint.sh — do not edit manually.
\$host = "${DB_HOST}";
\$user = "${DB_USER}";
\$pass = "${DB_PASS}";
\$db   = "${DB_NAME}";

\$conn = mysqli_connect(\$host, \$user, \$pass, \$db);

if (!\$conn) {
    die("Database connection failed: " . mysqli_connect_error());
}

mysqli_set_charset(\$conn, "utf8mb4");
PHP

echo "[entrypoint] db.php generated (host=${DB_HOST}, db=${DB_NAME})"

# Execute the CMD passed to the container (apache2-foreground)
exec "$@"
